development:
    baseUrl: 'https://hedgeformac.dev'
    debug: true

staging:
    baseUrl: 'https://staging.hedgeformac.com'
    debug: true

production:
    baseUrl: 'https://www.hedgeformac.com'
    debug: false
